_BASE_: "Base-OVD-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNNMViT"
#  WEIGHTS: /22liushoulong/projects5/second/output/coco_ovd_PIS_second/model_0009999.pth
  PIS_PROP_PATH: /22liushoulong/projects/object-centric-ovd/datasets/MAVL_proposals/coco_props/class_specific # change to your path
  VLM_TRAIN_DES_PATH: /22liushoulong/datasets/ZSFooD2/new_ins_des_train/
  VLM_EVAL_DES_PATH: /22liushoulong/datasets/ZSFooD2/new_ins_des_val/
  ROI_BOX_HEAD:
    WEIGHT_TRANSFER: False
    WS_NUM_PROPS: 32
    IMAGE_LABEL_LOSS: 'pseudo_max_score'
SOLVER:
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
DATASETS:
#  TRAIN: ("coco_zeroshot_train_oriorder","coco_caption_train_tags")
  TRAIN: ("coco_zeroshot_train_oriorder",)
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (800, 800)
  TEST_INPUT_TYPE: 'custom_with_vlm'
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4, 16] # Batch-size per GPU
  USE_RFS: [False, False]
  DATASET_MIN_SIZES: [[800, 800], [400, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: False
OUTPUT_DIR: output/coco_ovd_PIS_second_NO_CAP_two
TEST:
  EVAL_PERIOD: 5000
